[package]
name = "goreecloud-backups-cli"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true
authors.workspace = true

[[bin]]
name = "goreecloud-backups"
path = "src/main.rs"

[dependencies]
goreecloud-backups-core = { path = "../backups-core" }
goreecloud-backups-repository = { path = "../backups-repository" }

[lints]
workspace = true
